micronaut.application.name=e2e-tests-micronaut
datasources.default.url=jdbc:tc:postgresql:18-alpine:///testdb?TC_INITSCRIPT=file:../test-scenarios-frameworks/all_tables_behavior/schema.sql
datasources.default.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
datasources.default.username=test
datasources.default.password=test
