CREATE TABLE type (
  smallserial_type smallserial,
  serial2_type serial2 NOT NULL,
  pg_serial2_type pg_catalog.serial2,
  serial_type serial,
  serial4_type serial4 NOT NULL,
  pg_serial4_type pg_catalog.serial4,
  bigserial_type bigserial,
  serial8_type serial8 NOT NULL,
  pg_serial8_type pg_catalog.serial8,
  smallint_type SMALLINT,
  int2_type int2 NOT NULL,
  pg_int2_type pg_catalog.int2,
  integer_type INTEGER,
  int_type INT,
  int4_type int4 NOT NULL,
  pg_int4_type pg_catalog.int4,
  bigint_type bigint,
  int8_type int8 NOT NULL,
  pg_int8_type pg_catalog.int8,
  real_type REAL,
  float4_type float4 NOT NULL,
  pg_float4_type pg_catalog.float4,
  float_type FLOAT,
  double_type DOUBLE PRECISION,
  float8_type float8 NOT NULL,
  pg_float8_type pg_catalog.float8,
  numeric_type NUMERIC,
  pg_numeric_type pg_catalog.numeric,
  bool_type bool,
  pg_bool_type pg_catalog.bool,
  jsonb_type jsonb,
  blob_type blob,
  text_type text,
  varchar_type VARCHAR,
  pg_varchar_type pg_catalog.varchar,
  bpchar_type bpchar,
  pg_bpchar_type pg_catalog.bpchar,
  string_type string NOT NULL
);
