packageName=example.typemappings
typeMapping.type.mood=com.example.CustomMood:com.example.CustomMoodAdapter
typeMapping.type.jsonb=com.example.JsonData:com.example.JsonDataAdapter
typeMapping.column.users.preferences=com.example.UserPreferences:com.example.UserPreferencesAdapter
