// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress(
  "DEPRECATION", "unused", "UNUSED_PARAMETER", "ClassName", "REDUNDANT_PROJECTION",
  "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
  "PLATFORM_CLASS_MAPPED_TO_KOTLIN", "IMPLICIT_NOTHING_TYPE_ARGUMENT_IN_RETURN_POSITION",
)

package com.pkware.norm.generator

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import kotlin.String
import kotlin.Suppress
import kotlin.collections.emptySet
import kotlin.text.buildString

public class KotlinPluginOptionsJsonAdapter(
  moshi: Moshi,
) : JsonAdapter<KotlinPluginOptions>() {
  private val options: JsonReader.Options = JsonReader.Options.of("packageName")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(
    String::class.java,
    emptySet(),
    "packageName",
  )

  public override fun toString(): String = buildString(41) {
    append("GeneratedJsonAdapter(").append("KotlinPluginOptions").append(')')
  }

  public override fun fromJson(reader: JsonReader): KotlinPluginOptions {
    var packageName: String? = null
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> packageName = stringAdapter.fromJson(reader)
          ?: throw Util.unexpectedNull("packageName", "packageName", reader)
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    return KotlinPluginOptions(
      packageName = packageName ?: throw Util.missingProperty(
        "packageName",
        "packageName",
        reader,
      ),
    )
  }

  public override fun toJson(writer: JsonWriter, value_: KotlinPluginOptions?) {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("packageName")
    stringAdapter.toJson(writer, value_.packageName)
    writer.endObject()
  }
}
