micronaut.application.name=norm-example
datasources.default.url=jdbc:postgresql://localhost:5432/postgres
datasources.default.username=postgres
datasources.default.password=
datasources.default.driver-class-name=org.postgresql.Driver
