# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test

on:
  pull_request:
  push:
    branches: [ main, release/* ]

permissions: {}

jobs:
  linux:
    name: Linux (Postgres ${{ matrix.pg-version }})
    strategy:
      fail-fast: false
      matrix:
        pg-version: [16, 17, 18]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 25
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0 # zizmor: ignore[cache-poisoning]

      - name: Clear Testcontainers cache
        run: rm -f ~/.testcontainers.properties

      - name: Build Norm
        run: ./gradlew build -Dnorm.test.pgVersion=${{ matrix.pg-version }}

      - name: Verify golden files are up to date
        if: matrix.pg-version == 18
        run: |
          ./gradlew :gradle-plugin:generateGoldenFiles
          git diff --exit-code -- test-scenarios/ test-scenarios-frameworks/

      - name: Build Example
        if: matrix.pg-version == 18
        run: ./gradlew build
        working-directory: example

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Test Results Linux PG ${{ matrix.pg-version }}
          path: '**/test-results/**/*.xml'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v6.4.2
        if: always()
        with:
          report_paths: '**/test-results/**/TEST-*.xml'
          check_name: Test Report (PG ${{ matrix.pg-version }})
